<!DOCTYPE html>
<html lang="en-us">
<head><meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Zora Zorkić</title>
<meta name="description" content="The personal website of Zora Zorkić">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://hzorkic.github.io/css/bootstrap.min.css">
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:400,300,700,400italic">
<link rel="stylesheet" href="https://hzorkic.github.io/css/font-awesome.min.css">
<link rel="stylesheet" href="https://hzorkic.github.io/css/owl.carousel.css">
<link rel="stylesheet" href="https://hzorkic.github.io/css/owl.theme.css">


  <link href="https://hzorkic.github.io/css/style.default.css" rel="stylesheet" id="theme-stylesheet">

 

  
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  


<link href="https://hzorkic.github.io/css/custom.css" rel="stylesheet">
<link rel="shortcut icon" href="https://hzorkic.github.io/img/favicon.png">



 
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.1/jquery.min.js" ></script> 

<script type="text/javascript" src="js/bigfoot.js"></script> 
<link rel="stylesheet" type="text/css" href="css/bigfoot.css"> 

<script type="text/javascript"> $.bigfoot(); </script> 
</head>
<body>
  <div id="all">
      <div class="container-fluid">
          <div class="row row-offcanvas row-offcanvas-left">
              <div id="sidebar" class="col-xs-6 col-sm-4 col-md-3 sidebar-offcanvas">
  <div class="sidebar-content" >
    
    <h1 class="sidebar-heading">
      <div class="hidden-xs"><img style="max-width: 70%; margin-bottom: 15px;  height: auto; border: 2px black solid; border-radius: 190px; max-height: 300px" src="/img/prof.png" alt=""></div>
      
      <a href="https://hzorkic.github.io/">
        
        <img src="https://see.fontimg.com/api/renderfont4/GOZEP/eyJyIjoiZnMiLCJoIjo2NSwidyI6MTAwMCwiZnMiOjY1LCJmZ2MiOiIjMDAwMDAwIiwiYmdjIjoiI0ZGRkZGRiIsInQiOjF9/em9yYSB6b3JraWM/sizelademo-regular.png" alt="Prehistoric fonts" style="height: auto; max-height: 80%; max-width: 100%; margin-bottom: 20px;">
      </a>
    </h1>
    
    
      <p class="sidebar-p" style="margin-bottom: 2px; ">Data Scientist.</p>
    
      <p class="sidebar-p" style="margin-bottom: 2px; ">UX Researcher.</p>
    
    
    
      <p class="sidebar-p" style="margin-top: 20px; "\>📍 Somewhere between Austin and San Diego </p>
    
    
   
    <ul class="sidebar-menu" style="margin-top: 20px; ">
      
        <li><a href="https://hzorkic.github.io/about/">About</a></li>
      
        <li><a href="https://hzorkic.github.io/portfolio/">Portfolio</a></li>
      
        <li><a href="https://hzorkic.github.io/blog/">Blog</a></li>
      
        <li><a href="https://docs.google.com/document/d/1kj4knE2wdZdFEqjAO-J8EwKpLbXFVES-eprmV8g3lqs/edit?usp=sharing">CV</a></li>
      
      
      
    </ul>
    <p class="social">
  
  
  
  
  
  <a href="mailto:hayley.zorkic@gmail.com" data-animate-hover="pulse" class="email" title="E-mail">
    <i class="fa fa-envelope"></i>
  </a>
  
  
  <a href="https://www.linkedin.com/in/hayley-zorkic" data-animate-hover="pulse" class="external" title="LinkedIn" rel="me">
    <i class="fa fa-linkedin"></i>
  </a>
  
  
  
  <a href="https://github.com/hzorkic" data-animate-hover="pulse" class="external" title="GitHub" rel="me">
    <i class="fa fa-github"></i>
  </a>
  
  
  
  
</p>

      <div class="copyright" style="font-size: 2px;">
        
      </div>
    
    
    

    
  </div>
</div>

              
<div class="col-xs-12 col-sm-8 col-md-9 content-column white-background">
  <div class="small-navbar visible-xs">
  <button type="button" data-toggle="offcanvas" class="btn btn-ghost">
    <i class="fa fa-bars"></i>
  </button>
  <h1 class="small-navbar-heading">
    <a href="https://hzorkic.github.io/">
      <img src="https://see.fontimg.com/api/renderfont4/GOZEP/eyJyIjoiZnMiLCJoIjo2NSwidyI6MTAwMCwiZnMiOjY1LCJmZ2MiOiIjMDAwMDAwIiwiYmdjIjoiI0ZGRkZGRiIsInQiOjF9/em9yYSB6b3JraWM/sizelademo-regular.png"
      style="max-height:30px;">
    </a>
  </h1>
</div>

  <div class="row">
    <div class="col-lg-8">
      <div class="content-column-content">
         <h1>Exploratory Data Analysis of SARS-CoV-2 Mutations</h1>
         
<script src="https://hzorkic.github.io/blog/2020-10-16-exploratory-data-analysis-of-sars-cov-2-mutations/index_files/header-attrs/header-attrs.js"></script>


<div id="introduction" class="section level3">
<h3>0. Introduction</h3>
<p>COVID-19 is an infectionus disease caused by Severe Acute Respiratory Syndrome Coronavirus 2 (SARS-CoV-2). First identified in December of 2019, SARS-CoV-2 resulted in an ongoing pandemic effecting over 39 million people in 189 countries, but the WHO predicts that with asymptomatic cases, the number of infections may be closer to 800 million.</p>
<p>Therapeutics for those suffering from COVID-19 include collecting and transplanting neautralizing antibodies from patients who have recoved from COVID-19. If there were a mutation on the spike protein region of SARS-CoV-2, this therapy may become ineffective as antibody neutralization is a highly specific mechanism. In this report, I will be combining two datasets that document protein sequence mutations in the spike domain region of SARS-CoV-2 samples obtained from pateints who were hospitalized for COVID-19-one from Houston and two from the COVID-19 Viral Genome Analysis Pipeline (GISAID).</p>
<p>It is important to note that the two datasets from the COVID-19 Viral Genome Analysis Pipeline were originally the same dataset. In the original excel spreadsheet, certain mutations were highlighted in yellow as areas of interest, while others remained white, so I separated the two for further filtering of the white cases.</p>
</div>
<div id="tidying" class="section level1">
<h1>1. Tidying</h1>
<p>First I will load in the datasets and name them. I have also loaded three crucial packages that will be used throughout this project.</p>
<pre class="r"><code>library(tidyverse)
library(ggpubr)
library(ggplot2)
HOU &lt;- read_csv(&quot;HOU.csv&quot;)
lanlHighlighted &lt;- read_csv(&quot;lanlH.csv&quot;)
lanlNotHighlighted &lt;- read_csv(&quot;lanlNH.csv&quot;)</code></pre>
<div id="tidy-task-1-lanl-highlighted-data-is-too-wide." class="section level4">
<h4>Tidy task 1: lanl Highlighted data is too wide.</h4>
<p>Lanl Highlighted included columns for each mutation, so I pivoted the data long into a new column named “mutations”, so that each mutation had its own row, and the original column names into a new column named “delete” that is promptly deleted. Next, I had to separate each mutation from its frequency in the cell, and remove the parenthesis around the frequencies. I named the frequency column with the dataset name for further analysis. From there I removed any row that did not have a meaningful mutation value (N/A, ” “, or X which means an unknown Amino Acid). Based on scientific opinion, I was directed to keep only those mutations with a frequency greater than or equal to 3.</p>
<pre class="r"><code>head(lanlHighlighted)</code></pre>
<pre><code>## # A tibble: 6 × 12
##   Region Position AA    Entropy `Mut 1` `Mut 2` `Mut 3` `Mut 4` `Mut 5` `Mut 6`
##   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  
## 1 &lt;NA&gt;          5 L       0.048 F(597)  I(1)    X(58)   &lt;NA&gt;    &lt;NA&gt;    &lt;NA&gt;   
## 2 &lt;NA&gt;         12 S       0.011 C(1)    F(107)  P(1)    X(8)    &lt;NA&gt;    &lt;NA&gt;   
## 3 &lt;NA&gt;         13 S       0.003 I(19)   N(6)    X(5)    &lt;NA&gt;    &lt;NA&gt;    &lt;NA&gt;   
## 4 &lt;NA&gt;         14 Q       0.003 &lt;NA&gt;    H(17)   R(3)    X(7)    &lt;NA&gt;    &lt;NA&gt;   
## 5 &lt;NA&gt;         15 C       0.002 &lt;NA&gt;    F(12)   X(6)    &lt;NA&gt;    &lt;NA&gt;    &lt;NA&gt;   
## 6 &lt;NA&gt;         16 V       0.001 &lt;NA&gt;    F(3)    I(1)    X(5)    &lt;NA&gt;    &lt;NA&gt;   
## # … with 2 more variables: Mut 7 &lt;chr&gt;, Mu 8 &lt;lgl&gt;</code></pre>
<pre class="r"><code>lanlHighlighted &lt;- lanlHighlighted %&gt;% 
  pivot_longer(5:12, names_to=&quot;delete&quot;, values_to=&quot;mutations&quot;) %&gt;%
  select(-delete) %&gt;% 
  separate(mutations,into=c(&quot;mutations&quot;,&quot;lanlHfrequency&quot;)) %&gt;%
  mutate(lanlHfrequency=(gsub(&quot;[() ]&quot;, &quot;&quot;, lanlHfrequency))) %&gt;%
  filter(!is.na(mutations), mutations!=&quot;&quot;,mutations!=&quot;X&quot;) %&gt;% 
  mutate_at(c(2,4,6), as.numeric) %&gt;%
  filter(lanlHfrequency&gt;=3)
head(lanlHighlighted)</code></pre>
<pre><code>## # A tibble: 6 × 6
##   Region Position AA    Entropy mutations lanlHfrequency
##   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;              &lt;dbl&gt;
## 1 &lt;NA&gt;          5 L       0.048 F                    597
## 2 &lt;NA&gt;         12 S       0.011 F                    107
## 3 &lt;NA&gt;         13 S       0.003 I                     19
## 4 &lt;NA&gt;         13 S       0.003 N                      6
## 5 &lt;NA&gt;         14 Q       0.003 H                     17
## 6 &lt;NA&gt;         14 Q       0.003 R                      3</code></pre>
<pre class="r"><code>nrow(lanlHighlighted)</code></pre>
<pre><code>## [1] 119</code></pre>
</div>
<div id="tidy-task2-lanl-not-highlighted-data-is-too-wide-as-well." class="section level4">
<h4>Tidy task2: lanl Not Highlighted data is too wide as well.</h4>
<p>Lanl Not Highlighted included columns for each mutation, so I pivoted the data long into a new column named “mutations”, so that each mutation had its own row, and the original column names into a new column named “delete” that is promptly deleted. Next, I had to separate each mutation from its frequency in the cell, and remove the parenthesis around the frequencies. I named the frequency column with the dataset name for further analysis. From there I removed any row that did not have a meaningful mutation value (N/A, ” “, or X which means an unknown Amino Acid). Based on professional scientific opinion, I was directed to keep only mutations at positions with more than three unique mutations and of those unique mutations, keep only those with a frequency of 5 or more.</p>
<pre class="r"><code>head(lanlNotHighlighted)</code></pre>
<pre><code>## # A tibble: 6 × 12
##   Region Position AA    Entropy `Mut 1` `Mut 2` `Mut 3` `Mut 4` `Mut 5` `Mut 6`
##   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  
## 1 &lt;NA&gt;          1 M       0.001 &lt;NA&gt;    X(7)    &lt;NA&gt;    &lt;NA&gt;    &lt;NA&gt;    &lt;NA&gt;   
## 2 &lt;NA&gt;          2 F       0.001 L(10)   X(3)    &lt;NA&gt;    &lt;NA&gt;    &lt;NA&gt;    &lt;NA&gt;   
## 3 &lt;NA&gt;          3 V       0.001 F(1)    G(4)    I(2)    X(24)   &lt;NA&gt;    &lt;NA&gt;   
## 4 &lt;NA&gt;          4 F       0     S(2)    X(5)    &lt;NA&gt;    &lt;NA&gt;    &lt;NA&gt;    &lt;NA&gt;   
## 5 &lt;NA&gt;          6 V       0.005 F(45)   I(1)    X(6)    &lt;NA&gt;    &lt;NA&gt;    &lt;NA&gt;   
## 6 &lt;NA&gt;          7 L       0.001 F(1)    I(1)    S(3)    V(1)    X(2)    &lt;NA&gt;   
## # … with 2 more variables: Mut 7 &lt;chr&gt;, Mu 8 &lt;lgl&gt;</code></pre>
<pre class="r"><code>lanlNotHighlighted &lt;- lanlNotHighlighted %&gt;%
  pivot_longer(5:12, names_to=&quot;delete&quot;, values_to=&quot;mutations&quot;) %&gt;%
  select(-delete) %&gt;% 
  separate(mutations,into=c(&quot;mutations&quot;,&quot;lanlNHfrequency&quot;)) %&gt;%
  mutate(lanlNHfrequency=(gsub(&quot;[() ]&quot;, &quot;&quot;, lanlNHfrequency))) %&gt;%
  filter(!is.na(mutations), mutations!=&quot;&quot;, mutations!=&quot;X&quot;) %&gt;% 
  mutate_at(c(2,4,6), as.numeric) %&gt;%
  group_by(Position) %&gt;% 
  filter(n()&gt;=3) %&gt;%
  filter(lanlNHfrequency&gt;=5)
head(lanlNotHighlighted)</code></pre>
<pre><code>## # A tibble: 6 × 6
## # Groups:   Position [3]
##   Region Position AA    Entropy mutations lanlNHfrequency
##   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt;
## 1 &lt;NA&gt;          8 L       0.006 F                       6
## 2 &lt;NA&gt;          8 L       0.006 V                      45
## 3 &lt;NA&gt;          9 P       0.002 L                       8
## 4 &lt;NA&gt;          9 P       0.002 S                       8
## 5 &lt;NA&gt;         22 T       0.009 I                      34
## 6 &lt;NA&gt;         22 T       0.009 N                      39</code></pre>
<pre class="r"><code>nrow(lanlNotHighlighted)</code></pre>
<pre><code>## [1] 150</code></pre>
</div>
<div id="tidy-task-3-combining-lanlnothighlighted-and-lanlhighlighted" class="section level4">
<h4>Tidy task 3: Combining lanlNotHighlighted and lanlHighlighted</h4>
<p>To simplify the lanl datasets, I combined them with full_join- the number of rows in lanlHightlighted is 119, the number of rows in lanlNotHighlighted is 150, and the number of rows in the joined dataset is the sum of these two numbers- 269- which makes sense because the Highlighted data points were extracted and removed from the orignial dataset separating it into Highlighted and NonHighlighted, so there should not be any overlapping cases.</p>
<pre class="r"><code>lanlTOT &lt;- lanlHighlighted %&gt;% full_join(lanlNotHighlighted, by=c(&quot;Position&quot;, &quot;AA&quot;, &quot;Entropy&quot;,&quot;Region&quot;,&quot;mutations&quot;))
head(lanlTOT)</code></pre>
<pre><code>## # A tibble: 6 × 7
##   Region Position AA    Entropy mutations lanlHfrequency lanlNHfrequency
##   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;              &lt;dbl&gt;           &lt;dbl&gt;
## 1 &lt;NA&gt;          5 L       0.048 F                    597              NA
## 2 &lt;NA&gt;         12 S       0.011 F                    107              NA
## 3 &lt;NA&gt;         13 S       0.003 I                     19              NA
## 4 &lt;NA&gt;         13 S       0.003 N                      6              NA
## 5 &lt;NA&gt;         14 Q       0.003 H                     17              NA
## 6 &lt;NA&gt;         14 Q       0.003 R                      3              NA</code></pre>
<pre class="r"><code>nrow(lanlTOT)</code></pre>
<pre><code>## [1] 269</code></pre>
</div>
<div id="tidy-task-4-hou-data-is-too-wide." class="section level4">
<h4>Tidy task 4: Hou data is too wide.</h4>
<p>The Hou data was decently clean. After removing a few empty columns, I filtered for rows that did not have a meaningful mutation value (NA, ““, or X). Based on professional scientific opinion, I was directed to keep any mutations with frequencies of 5 or more AND/OR mutations with 3 or more unique mutations at a given position. I did this by independently filtering the HOU dataset for frequency greater than or equal to 5, more than three unique mutations, and then preforming a full join of the data to capture all instances of these cases that occur independently OR simmotaneously- preventing duplicate rows.</p>
<pre class="r"><code>head(HOU)</code></pre>
<pre><code>## # A tibble: 6 × 8
##   Region Position AA    mutations count ...6  ...7  ...8 
##   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;lgl&gt; &lt;lgl&gt; &lt;lgl&gt;
## 1 &lt;NA&gt;          5 L     F            36 NA    NA    NA   
## 2 &lt;NA&gt;          6 V     F             1 NA    NA    NA   
## 3 &lt;NA&gt;          9 P     S             2 NA    NA    NA   
## 4 &lt;NA&gt;          9 P     L             2 NA    NA    NA   
## 5 &lt;NA&gt;         11 V     A             1 NA    NA    NA   
## 6 &lt;NA&gt;         12 S     F             6 NA    NA    NA</code></pre>
<pre class="r"><code>nrow(HOU)</code></pre>
<pre><code>## [1] 286</code></pre>
<pre class="r"><code>hou5 &lt;- HOU %&gt;% select(-c(6:8)) %&gt;% filter(!is.na(mutations), mutations!=&quot;&quot;, mutations!=&quot;X&quot;) %&gt;% mutate(HOUfrequency=as.numeric(count)) %&gt;% select(-count) %&gt;% filter(HOUfrequency&gt;=5) 
head(hou5)</code></pre>
<pre><code>## # A tibble: 6 × 5
##   Region Position AA    mutations HOUfrequency
##   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;            &lt;dbl&gt;
## 1 &lt;NA&gt;          5 L     F                   36
## 2 &lt;NA&gt;         12 S     F                    6
## 3 NTD          18 L     F                   12
## 4 NTD          21 R     I                    6
## 5 NTD          22 T     I                    6
## 6 NTD          26 P     S                   17</code></pre>
<pre class="r"><code>nrow(hou5)</code></pre>
<pre><code>## [1] 43</code></pre>
<pre class="r"><code>hou3AA &lt;- HOU %&gt;% select(-c(6:8)) %&gt;% filter(!is.na(mutations), mutations!=&quot;&quot;,mutations!=&quot;X&quot;) %&gt;% group_by(Position) %&gt;% mutate(HOUfrequency=as.numeric(count)) %&gt;% select(-count) %&gt;% filter(n()&gt;=3) 
head(hou3AA)</code></pre>
<pre><code>## # A tibble: 6 × 5
## # Groups:   Position [2]
##   Region Position AA    mutations HOUfrequency
##   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;            &lt;dbl&gt;
## 1 NTD          21 R     I                    6
## 2 NTD          21 R     K                    1
## 3 NTD          21 R     T                    3
## 4 NTD          27 A     S                    2
## 5 NTD          27 A     T                    1
## 6 NTD          27 A     V                    1</code></pre>
<pre class="r"><code>nrow(hou3AA)</code></pre>
<pre><code>## [1] 18</code></pre>
<pre class="r"><code>houTOT&lt;- hou5 %&gt;% full_join(hou3AA, by=c(&quot;Position&quot;, &quot;AA&quot;, &quot;HOUfrequency&quot;, &quot;Region&quot;, &quot;mutations&quot;))
head(houTOT)</code></pre>
<pre><code>## # A tibble: 6 × 5
##   Region Position AA    mutations HOUfrequency
##   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;            &lt;dbl&gt;
## 1 &lt;NA&gt;          5 L     F                   36
## 2 &lt;NA&gt;         12 S     F                    6
## 3 NTD          18 L     F                   12
## 4 NTD          21 R     I                    6
## 5 NTD          22 T     I                    6
## 6 NTD          26 P     S                   17</code></pre>
<pre class="r"><code>nrow(houTOT)</code></pre>
<pre><code>## [1] 59</code></pre>
</div>
<div id="tidy-task-5-combining-lanltot-and-houtot" class="section level4">
<h4>Tidy task 5: Combining lanlTOT and houTOT</h4>
<p>To combine lanlTOT and HOU, I performed a full join between houTOT and lanlTOT. I did a full join because I wanted to create a tabel where each row represented a single unqiue Amino Acid mutation that was in either houTOT, lanlTOT, OR both of them. There were 269 rows lanlTOT and 59 rows in houTOT,but 312 rows in the fully joined dataset. This means 16 of the filtered Amino Acid mutations occured in both lanlTOT and houTOT. In addition to combining these datasets, I made a new column that gives the total frequency of each mutation by summing the frequencies from lanlHighlighted, lanlNotHighlighted, and HOU into a new column names TOTfrequency for further analysis.</p>
<pre class="r"><code>lanlhouTOT &lt;- houTOT %&gt;% full_join(lanlTOT, by=c(&quot;Position&quot;,&quot;mutations&quot;,&quot;AA&quot;, &quot;Region&quot;))  %&gt;%  mutate(TOTfrequency = select(.,HOUfrequency, lanlHfrequency, lanlNHfrequency) %&gt;% rowSums(na.rm = TRUE)) %&gt;% arrange(Position)
head(lanlhouTOT)</code></pre>
<pre><code>## # A tibble: 6 × 9
##   Region Position AA    mutations HOUfrequency Entropy lanlHfrequency
##   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;            &lt;dbl&gt;   &lt;dbl&gt;          &lt;dbl&gt;
## 1 &lt;NA&gt;          5 L     F                   36   0.048            597
## 2 &lt;NA&gt;          8 L     F                   NA   0.006             NA
## 3 &lt;NA&gt;          8 L     V                   NA   0.006             NA
## 4 &lt;NA&gt;          9 P     L                   NA   0.002             NA
## 5 &lt;NA&gt;          9 P     S                   NA   0.002             NA
## 6 &lt;NA&gt;         12 S     F                    6   0.011            107
## # … with 2 more variables: lanlNHfrequency &lt;dbl&gt;, TOTfrequency &lt;dbl&gt;</code></pre>
<pre class="r"><code>nrow(lanlhouTOT)</code></pre>
<pre><code>## [1] 312</code></pre>
</div>
</div>
<div id="summary-statistics" class="section level1">
<h1>2. Summary Statistics</h1>
<p>I calculated some summary statistics for my data including min,max,mean,and sd for the numeric variables in my dataset- TOTfrequency, Entropy, and Position as a whole and then after grouping by Region. I elected not to group_by Region and any other of my categorical variables because it would not make sense to group by Amino Acid or the Amino Acid the original mutated to. There are only 20 Amino Acids, but what makes each mutation unqiue is its original Amino Acid, its Position, AND its mutation all together. These statistics show that there are 12 distinct regions within the dataset, 312 distinct mutations represented between position 5 and 1263, with an average mutation freequncy of 244.3814 and an average entropy of .01. The maximum values for Entropy and Mutation frequency re strikingly large compared to their means- Entropy 0.5 and Mutation frequency at 58,538- it appears there is a very common mutation in the data.</p>
<p>When grouping by region, we can see that there are regions with significant variation and frequency of mutations-SD2 with an average frequency of 2040, but with a standard deviation of 10,866 and RBM with an average frequency of 231, but a standard deviation of 846. It is also interesting to note that these two regions with significantly higher mean mutation frequency have entropy values that are also higher and more spread- SD2 with an average entropy of 0.06 and sd of .15 and RBM with an average frequency of .03 and sd of .06.</p>
<pre class="r"><code>#summary functions used: mean,sd,n_distinct
statSum &lt;- lanlhouTOT %&gt;% summarise(distinctRegions= n_distinct(Region), distinctMutations=nrow(lanlhouTOT), minMutFreq = min(TOTfrequency), maxMutFreq = max(TOTfrequency), avgMutFreq = mean(TOTfrequency), sdMutFreq=sd(TOTfrequency), minEntropy = min(Entropy, na.rm = TRUE), maxEntropy = max(Entropy, na.rm = TRUE), avgEntropy = mean(Entropy, na.rm = TRUE), sdEntropy=sd(Entropy, na.rm = TRUE), minPosition = min(Position), maxPosition = max(Position), avgPosition = mean(Position), sdPosition=sd(Position))
statSum</code></pre>
<pre><code>## # A tibble: 1 × 14
##   distinctRegions distinctMutations minMutFreq maxMutFreq avgMutFreq sdMutFreq
##             &lt;int&gt;             &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
## 1              12               312          1      58538       244.     3329.
## # … with 8 more variables: minEntropy &lt;dbl&gt;, maxEntropy &lt;dbl&gt;,
## #   avgEntropy &lt;dbl&gt;, sdEntropy &lt;dbl&gt;, minPosition &lt;dbl&gt;, maxPosition &lt;dbl&gt;,
## #   avgPosition &lt;dbl&gt;, sdPosition &lt;dbl&gt;</code></pre>
<pre class="r"><code>#Explore Region
statSumByRegion &lt;- lanlhouTOT %&gt;% group_by(Region) %&gt;% summarise(distinctMutations=n_distinct(TOTfrequency), minMutFreq = min(TOTfrequency), maxMutFreq = max(TOTfrequency), avgMutFreq = mean(TOTfrequency), sdMutFreq=sd(TOTfrequency), minEntropy = min(Entropy, na.rm = TRUE), maxEntropy = max(Entropy, na.rm = TRUE), avgEntropy = mean(Entropy, na.rm = TRUE), sdEntropy=sd(Entropy, na.rm = TRUE), minPosition = min(Position), maxPosition = max(Position), avgPosition = mean(Position), sdPosition=sd(Position))
statSumByRegion</code></pre>
<pre><code>## # A tibble: 12 × 14
##    Region distinctMutations minMutFreq maxMutFreq avgMutFreq sdMutFreq minEntropy
##    &lt;chr&gt;              &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
##  1 CD                     8          5         95      21.3      28.3       0.001
##  2 CH                     3          5         51      26.3      23.2       0.009
##  3 FP                     6          3        117      33.6      46.9       0.001
##  4 HR1                   11          3        743      67       196.        0    
##  5 HR2                    4          5         56      24.8      21.9       0.001
##  6 NTD                   41          1        378      23.2      43.5       0.001
##  7 RBD                    5          5         23       9.25      5.90      0.002
##  8 RBM                   12          3       3400     231.      846.        0.001
##  9 SD1                    4          6         18      12.6       6.07      0.002
## 10 SD2                   19          3      58538    2040.    10866.        0.001
## 11 TM                     2         29         52      40.5      16.3       0.01 
## 12 &lt;NA&gt;                  48          1       4895      78.5     453.        0.001
## # … with 7 more variables: maxEntropy &lt;dbl&gt;, avgEntropy &lt;dbl&gt;, sdEntropy &lt;dbl&gt;,
## #   minPosition &lt;dbl&gt;, maxPosition &lt;dbl&gt;, avgPosition &lt;dbl&gt;, sdPosition &lt;dbl&gt;</code></pre>
<div id="visualizing" class="section level3">
<h3>3. Visualizing</h3>
<div id="correlation-heatmap" class="section level4">
<h4>Correlation Heatmap</h4>
<p>I calculated a correlation matrix for my numeric variables- only those that had all three numeric variables were considered- I did this by using cor(use=“pair”) so the correlation or covariance between each pair of variables is computed using all complete pairs of observations on those variables.From the correlation matrix we can see that there is a perfect correlation between the highlighted lanl frequency and the total frequency, a strong correlation beteen all frequencies with the total frequencies, and a medium correlation between entropy and frequency values. These correlations can be better visualized in the heatmap below.</p>
<pre class="r"><code>cormat &lt;- lanlhouTOT %&gt;% select_if(is.numeric) %&gt;% cor(use=&quot;pair&quot;) %&gt;% round(4)
cormat</code></pre>
<pre><code>##                 Position HOUfrequency Entropy lanlHfrequency lanlNHfrequency
## Position          1.0000       0.0174  0.0064         0.0223          0.0688
## HOUfrequency      0.0174       1.0000  0.1748         0.4923          0.6892
## Entropy           0.0064       0.1748  1.0000         0.5531          0.6012
## lanlHfrequency    0.0223       0.4923  0.5531         1.0000              NA
## lanlNHfrequency   0.0688       0.6892  0.6012             NA          1.0000
## TOTfrequency      0.0084       0.9811  0.5558         1.0000          0.9935
##                 TOTfrequency
## Position              0.0084
## HOUfrequency          0.9811
## Entropy               0.5558
## lanlHfrequency        1.0000
## lanlNHfrequency       0.9935
## TOTfrequency          1.0000</code></pre>
<pre class="r"><code>cormat %&gt;%
  as.data.frame%&gt;%
  rownames_to_column%&gt;%
  pivot_longer(-1)%&gt;%
  ggplot(aes(rowname,name,fill=value))+geom_tile()+
  geom_text(aes(label=round(value,3)))+
  xlab(&quot;&quot;)+ylab(&quot;&quot;)+coord_fixed()+
  scale_fill_gradient2(low=&quot;blue&quot;,mid=&quot;white&quot;,high=&quot;blue&quot;)+
  theme(axis.text.x = element_text(angle=45, hjust=1))</code></pre>
<p><img src="https://hzorkic.github.io/blog/2020-10-16-exploratory-data-analysis-of-sars-cov-2-mutations/index_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="mutation-frequency-hisotgram" class="section level4">
<h4>Mutation Frequency Hisotgram</h4>
<p>In this histogram, it is incredibly edivent that there is a mutation around 614 that occurs in high frequency; from its color, we can see that is a substitution to a G Amino Acid. I have separated the x axis into the spike domain regions of caronaviruses mentioned below which roughly correspond to the Region positions derived from the data: NTD 0-350, RBD 318-513, SD1 514-575, SD2 576-662, HR1 894-966, FP 798-809. The high frequency mutation is in SD2 as we predicted with the stats above.</p>
<pre class="r"><code>ggplot(data=lanlhouTOT,aes(x=Position)) +
  geom_col(aes(y=TOTfrequency, colour=mutations, fill=mutations))+
  scale_x_continuous(breaks=c(0,292,318, 513,575, 662, 894,966, 798,809))+
  ylab(&quot;Frequency of Mutations&quot;)+
  ggtitle(&quot;Histogram of LANL and HOU Data Mutations&quot;)+guides(col = guide_legend(nrow = 10))+theme_classic()+
  theme(axis.text.x = element_text(angle=90, hjust=1))</code></pre>
<p><img src="https://hzorkic.github.io/blog/2020-10-16-exploratory-data-analysis-of-sars-cov-2-mutations/index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
<div id="line-graph-average-totfrequency-vs-entropy" class="section level4">
<h4>Line Graph: Average TOTfrequency vs Entropy</h4>
<p>Fromt this bar graph, we can see that there are a few regions of interest where there not only are there large average mutation frequencies, but there is also large values for Entropy. There are, two points that are clearly more entropic and frequent than the rest- both correspond to the two spikes that are visible in the Bar plot above. Aside from these two lines, the rest of the lines remain pretty uniform with regards to their average mutation frequency and entropy- a slight positive linear relationship between the two variables- as average Frequency of mutations goes up, so does entropy!</p>
<pre class="r"><code>ggplot(data=lanlhouTOT,aes(x=Entropy, y=TOTfrequency,colour=Region, fill=Region)) +
  stat_summary(fun.y=mean, geom=&quot;line&quot;, alpha=.5,size=1)+
  ylab(&quot;Average Frequency of Mutations&quot;)+
  ggtitle(&quot;Linear Graph of Average TOTfrequency vs Entropy&quot;)+
  guides(col = guide_legend(nrow = 10))+theme_classic()+
  theme(axis.text.x = element_text(angle=90, hjust=1))</code></pre>
<p><img src="https://hzorkic.github.io/blog/2020-10-16-exploratory-data-analysis-of-sars-cov-2-mutations/index_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
<div id="mutation-frequency-hisotgram-by-region" class="section level4">
<h4>Mutation Frequency Hisotgram by Region</h4>
<p>In the prior histogram, it is difficult to see what OTHER mutations are occuring in the spike domain region. In the following visualization, I “zoom-in” to each region so we can observe if there are other regions with alot of mutations or high frequency mutations as well. There are several mutation point in NTD and FP, and there appears to be mutation frequencies above 200 in most of the domains as well. Regions of intrest include the spike in mutations in the RBD which is the Receptor Binding Domain and SD2 the Spike Domain 2, where SARS-CoV-2 binds to the ACE2 receptors on human cells and also a region where neutralizing antibodies bind- this is porblematic because it shows that antibody therapy may be less effective in the “next wave” of COVID-19 viruses.</p>
<pre class="r"><code>NTD2 &lt;- ggplot(data=lanlhouTOT, aes(x=Position)) +
  geom_col(aes(y=TOTfrequency, colour=mutations, fill=mutations))+
  ylab(&quot;Frequency of Mutations&quot;)+
  xlim(c(0,350))+
  coord_cartesian(ylim=c(0,200))+
  ggtitle(&quot;NTD&quot;)+
  theme_classic()

RBD2 &lt;- ggplot(data=lanlhouTOT, aes(x=Position)) +
  geom_col(aes(y=TOTfrequency, colour=mutations, fill=mutations))+
  ylab(&quot;Frequency of Mutations&quot;)+
  xlim(c(318,513))+
  coord_cartesian(ylim=c(0,200))+
  ggtitle(&quot;RBD&quot;)+
  theme_classic()


SD12 &lt;- ggplot(data=lanlhouTOT, aes(x=Position)) +
  geom_col(aes(y=TOTfrequency, colour=mutations, fill=mutations))+
  ylab(&quot;Frequency of Mutations&quot;)+
  xlim(c(514,575))+
  coord_cartesian(ylim=c(0,200))+
  ggtitle(&quot;SD1&quot;)+
  theme_classic()


SD22 &lt;- ggplot(data=lanlhouTOT, aes(x=Position)) +
  geom_col(aes(y=TOTfrequency, colour=mutations, fill=mutations))+
  ylab(&quot;Frequency of Mutations&quot;)+
  xlim(c(576,662))+
  coord_cartesian(ylim=c(0,200))+
  ggtitle(&quot;SD2&quot;)+
  theme_classic()


HR12 &lt;- ggplot(data=lanlhouTOT, aes(x=Position)) +
  geom_col(aes(y=TOTfrequency, colour=mutations, fill=mutations))+
  ylab(&quot;Frequency of Mutations&quot;)+
  xlim(c(894,966))+
  coord_cartesian(ylim=c(0,200))+
  ggtitle(&quot;HR1&quot;)+
  theme_classic()


FP2 &lt;- ggplot(data=lanlhouTOT, aes(x=Position)) +
  geom_col(aes(y=TOTfrequency, colour=mutations, fill=mutations))+
  ylab(&quot;Frequency of Mutations&quot;)+
  xlim(c(798,892))+
  coord_cartesian(ylim=c(0,200))+
  ggtitle(&quot;FP&quot;)+
  theme_classic()


CD2 &lt;- ggplot(data=lanlhouTOT, aes(x=Position)) +
  geom_col(aes(y=TOTfrequency, colour=mutations, fill=mutations))+
  ylab(&quot;Frequency of Mutations&quot;)+
  xlim(c(1055,1206))+
  coord_cartesian(ylim=c(0,200))+
  ggtitle(&quot;CH+BH+SD3&quot;)+
  theme_classic()


ggarrange(NTD2, RBD2, SD12, SD22, FP2,HR12, CD2,
                        nrow = 2, ncol = 4,common.legend = TRUE, legend = &quot;bottom&quot;)</code></pre>
<p><img src="https://hzorkic.github.io/blog/2020-10-16-exploratory-data-analysis-of-sars-cov-2-mutations/index_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
</div>
</div>
<div id="k-meanspam-clustering" class="section level3">
<h3>4. k-means/PAM clustering</h3>
<p>In the following chuck I will perform a k-means clustering for numeric and categorical variables with my data.</p>
<p>First, I curate a subset of my data with numeric variables and categorical Regions (which i change to factors). I excluded all except for the tot frequency column so that I could omit NAs in the data. This is problematic as I may lose valuable data.I compuete the gower dissimilarities.</p>
<pre class="r"><code>#install.packages(&quot;GGally&quot;)
library(cluster)
clust_dat &lt;- lanlhouTOT %&gt;% mutate_if(is.character,as.factor) %&gt;%  select(-c(HOUfrequency, lanlHfrequency, lanlNHfrequency, mutations, AA)) %&gt;% na.omit()

gower1&lt;-daisy(clust_dat,metric=&quot;gower&quot;)</code></pre>
<p>Next, I pick the optimal number of cluthers based on silhouette width. From the graph, it appears that 10 is the best number of clusters is 10!</p>
<pre class="r"><code>sil_width&lt;-vector()
for(i in 2:10){  
  pam_fit &lt;- pam(gower1, diss = TRUE, k = i)  
  sil_width[i] &lt;- pam_fit$silinfo$avg.width  
}

ggplot()+geom_line(aes(x=1:10,y=sil_width))+scale_x_continuous(name=&quot;k&quot;,breaks=1:10)</code></pre>
<p><img src="https://hzorkic.github.io/blog/2020-10-16-exploratory-data-analysis-of-sars-cov-2-mutations/index_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Next, I use the gower dissimilarities to perform clustering with PAM</p>
<pre class="r"><code>pam10 &lt;- pam(gower1, k = 10, diss = T) #tell pam you are using dissimilarities
pam10</code></pre>
<pre><code>## Medoids:
##        ID    
##  [1,]  40  40
##  [2,]  84  84
##  [3,]  90  90
##  [4,] 105 105
##  [5,] 123 123
##  [6,] 111 111
##  [7,] 140 140
##  [8,] 150 150
##  [9,] 159 159
## [10,] 166 166
## Clustering vector:
##   [1]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
##  [26]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
##  [51]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
##  [76]  1  1  1  1  1  2  2  2  2  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
## [101]  2  2  4  4  4  4  4  5  6  6  6  5  5  5  5  5  5  5  5  5  5  5  5  5  5
## [126]  5  5  5  5  5  5  5  5  5  5  5  7  7  7  7  7  7  8  8  8  8  8  8  8  8
## [151]  8  8  8  9  9  9  9  9  9  9  9  9  9  9 10 10 10 10 10 10
## Objective function:
##      build       swap 
## 0.02063839 0.01876176 
## 
## Available components:
## [1] &quot;medoids&quot;    &quot;id.med&quot;     &quot;clustering&quot; &quot;objective&quot;  &quot;isolation&quot; 
## [6] &quot;clusinfo&quot;   &quot;silinfo&quot;    &quot;diss&quot;       &quot;call&quot;</code></pre>
<p>Now I want to find the min and max distances between Positions. It looks like positions 4 and 110 are the least similar and 28 and 29 are the most similar.</p>
<pre class="r"><code>gower1%&gt;%as.matrix%&gt;%as.data.frame%&gt;%rownames_to_column%&gt;%
  pivot_longer(-1,values_to=&quot;distance&quot;)%&gt;%
  filter(rowname!=name)%&gt;%filter(distance%in%c(min(distance),max(distance)))%&gt;%
  distinct(distance,.keep_all = T)</code></pre>
<pre><code>## # A tibble: 2 × 3
##   rowname name  distance
##   &lt;chr&gt;   &lt;chr&gt;    &lt;dbl&gt;
## 1 4       110      0.872
## 2 28      29       0</code></pre>
<p>What do the clusters look like? Here I calculate summary statistics for the numeric variables by cluster. Cluster 6 is high average Entrpy and High average TOT frequency of mutations, cluster 3 also has high average entropy and average TOT frequency values. Cluster 10 has the almost three times the MEDIAN TOT frequency of cluster 6. All things considered,</p>
<pre class="r"><code>clust_dat%&gt;%mutate(cluster=pam10$clustering)%&gt;%group_by(cluster)%&gt;%
  rename_all(function(x)str_replace(x,&quot;_&quot;,&quot;&quot;))%&gt;%
  summarize_if(is.numeric,.funs = list(&quot;mean&quot;=mean,&quot;median&quot;=median,&quot;sd&quot;=sd),na.rm=T)%&gt;%
  pivot_longer(contains(&quot;_&quot;))%&gt;%
  separate(name,sep=&quot;_&quot;,into=c(&quot;variable&quot;,&quot;stat&quot;))%&gt;%
  pivot_wider(names_from = &quot;variable&quot;,values_from=&quot;value&quot;)%&gt;%arrange(stat)</code></pre>
<pre><code>## # A tibble: 30 × 5
##    cluster stat  Position Entropy TOTfrequency
##      &lt;int&gt; &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;        &lt;dbl&gt;
##  1       1 mean      168. 0.00625         24.2
##  2       2 mean      435. 0.00217         10  
##  3       3 mean      475. 0.0277         231. 
##  4       4 mean      556. 0.0032          12.6
##  5       5 mean      652. 0.00592         23.6
##  6       6 mean      614  0.498        19516. 
##  7       7 mean      829. 0.006           27.8
##  8       8 mean      934. 0.0129          84  
##  9       9 mean     1085. 0.00536         23.4
## 10      10 mean     1188. 0.00733         30  
## # … with 20 more rows</code></pre>
<p>What do the clusters look like? Proportions of Region by cluster. Cluster 1 is 100%NTD, cluster 2 is 100%RBD, cluster 3 is 100%RBM, cluster 4 is 100% SD1, cluster 5 is 100% SD2, cluster 6 is also 100% SD2, cluster 7 is 100% FP, cluster 8 is 100% HR1, cluster 9 is 82% CD and 19% CH, cluster 10 is 67% HR2 and.</p>
<pre class="r"><code>clust_dat %&gt;%mutate(cluster=factor(pam10$clustering))%&gt;%select(cluster,Region)%&gt;%
  group_by(cluster,Region)%&gt;%summarize(n=n())%&gt;%mutate(prop=n/sum(n,na.rm=T))%&gt;%
  pivot_wider(-n,names_from=Region,values_from=prop)</code></pre>
<pre><code>## # A tibble: 10 × 12
## # Groups:   cluster [10]
##    cluster   NTD   RBD   RBM   SD1   SD2    FP   HR1     CD     CH    HR2     TM
##    &lt;fct&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
##  1 1           1    NA    NA    NA    NA    NA    NA NA     NA     NA     NA    
##  2 2          NA     1    NA    NA    NA    NA    NA NA     NA     NA     NA    
##  3 3          NA    NA     1    NA    NA    NA    NA NA     NA     NA     NA    
##  4 4          NA    NA    NA     1    NA    NA    NA NA     NA     NA     NA    
##  5 5          NA    NA    NA    NA     1    NA    NA NA     NA     NA     NA    
##  6 6          NA    NA    NA    NA     1    NA    NA NA     NA     NA     NA    
##  7 7          NA    NA    NA    NA    NA     1    NA NA     NA     NA     NA    
##  8 8          NA    NA    NA    NA    NA    NA     1 NA     NA     NA     NA    
##  9 9          NA    NA    NA    NA    NA    NA    NA  0.818  0.182 NA     NA    
## 10 10         NA    NA    NA    NA    NA    NA    NA NA     NA      0.667  0.333</code></pre>
<p>What do clusters look like? Proportions of cluster assignment by Region. Clusters are assigned relatively evenly to clusters. Cluster 10 has Region HR1 and TM. Cluster six has a very small proportion of SD2 while cluster 5 has a large portino of the SD2 Region. Other than that, each cluster corresponds to one Region.</p>
<pre class="r"><code>clust_dat%&gt;%mutate(cluster=factor(pam10$clustering))%&gt;%select_if(negate(is.numeric))%&gt;%
  group_by(Region,cluster)%&gt;%summarize(n=n())%&gt;%mutate(prop=n/sum(n))%&gt;%
  pivot_wider(-n,names_from=Region,values_from=prop)</code></pre>
<pre><code>## # A tibble: 10 × 12
##    cluster    CD    CH    FP   HR1   HR2   NTD   RBD   RBM   SD1    SD2    TM
##    &lt;fct&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1 9           1     1    NA    NA    NA    NA    NA    NA    NA NA        NA
##  2 7          NA    NA     1    NA    NA    NA    NA    NA    NA NA        NA
##  3 8          NA    NA    NA     1    NA    NA    NA    NA    NA NA        NA
##  4 10         NA    NA    NA    NA     1    NA    NA    NA    NA NA         1
##  5 1          NA    NA    NA    NA    NA     1    NA    NA    NA NA        NA
##  6 2          NA    NA    NA    NA    NA    NA     1    NA    NA NA        NA
##  7 3          NA    NA    NA    NA    NA    NA    NA     1    NA NA        NA
##  8 4          NA    NA    NA    NA    NA    NA    NA    NA     1 NA        NA
##  9 5          NA    NA    NA    NA    NA    NA    NA    NA    NA  0.897    NA
## 10 6          NA    NA    NA    NA    NA    NA    NA    NA    NA  0.103    NA</code></pre>
<p>Which Regions are most representitive of their cluster? According to the Silhouette Plot, cluster 1,2,3,4,5,7,8 have a strong structure, clusters 6 and 9 have a reasonable structure, and cluster 10 has a weak structure and could be artificial. Considering the average width is .9, It is safe to say that the fit is strong.</p>
<pre class="r"><code>clust_dat %&gt;% slice(pam10$id.med)</code></pre>
<pre><code>## # A tibble: 10 × 4
##    Region Position Entropy TOTfrequency
##    &lt;fct&gt;     &lt;dbl&gt;   &lt;dbl&gt;        &lt;dbl&gt;
##  1 NTD         153   0.007           13
##  2 RBD         414   0.002            9
##  3 RBM         476   0.003           19
##  4 SD1         558   0.003           16
##  5 SD2         654   0.006            5
##  6 SD2         614   0.498            8
##  7 FP          831   0.005            3
##  8 HR1         938   0.002           12
##  9 CD         1085   0.002            8
## 10 HR2        1162   0.01            21</code></pre>
<pre class="r"><code>plot(pam10,which=2)</code></pre>
<p><img src="https://hzorkic.github.io/blog/2020-10-16-exploratory-data-analysis-of-sars-cov-2-mutations/index_files/figure-html/unnamed-chunk-19-1.png" width="960" /></p>
<pre class="r"><code>library(GGally)
ggpairs(clust_dat, aes(color=as.factor(pam10$clustering)))</code></pre>
<p><img src="https://hzorkic.github.io/blog/2020-10-16-exploratory-data-analysis-of-sars-cov-2-mutations/index_files/figure-html/unnamed-chunk-19-2.png" width="960" /></p>
</div>
<div id="closing-remarks" class="section level3">
<h3>5. Closing Remarks</h3>
<pre class="r"><code>lanlhouTOT %&gt;% arrange(desc(TOTfrequency)) %&gt;% head()</code></pre>
<pre><code>## # A tibble: 6 × 9
##   Region Position AA    mutations HOUfrequency Entropy lanlHfrequency
##   &lt;chr&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;            &lt;dbl&gt;   &lt;dbl&gt;          &lt;dbl&gt;
## 1 SD2         614 D     G                   NA   0.498          58538
## 2 &lt;NA&gt;        614 D     G                 4895  NA                 NA
## 3 RBM         477 S     N                   NA   0.19            3400
## 4 HR1         936 D     Y                    4   0.059            739
## 5 &lt;NA&gt;          5 L     F                   36   0.048            597
## 6 &lt;NA&gt;         21 R     I                   NA   0.043            506
## # … with 2 more variables: lanlNHfrequency &lt;dbl&gt;, TOTfrequency &lt;dbl&gt;</code></pre>
<p>From this exploratory data analysis, we have gathered that aside from the the mutations at position 614 and 477, the mutations occuring across the SAR-CoV-2 spike domain region in these data are standardized. The best way to cluster the data is in their domains. According to these data, it would be in scientists best interests to develop custom neutralizing antibody therapies and vaccines that have binding domains at the following positions that reflect the altered structures at the mutated spike domain locations.</p>
</div>
<div id="citations" class="section level3">
<h3>Citations:</h3>
<div id="scott-wesley-long-et.-al.-molecular-architecture-of-early-dissemination-and-massive-second-wave-of-the-sars-cov-2-virus-in-a-major-metropolitan-area.-medrxiv-2020.09.22.20199125-2020-doi-httpsdoi.org10.11012020.09.22.20199125" class="section level4">
<h4>Scott Wesley Long, Et. al. Molecular Architecture of Early Dissemination and Massive Second Wave of the SARS-CoV-2 Virus in a Major Metropolitan Area. medRxiv 2020.09.22.20199125 (2020); doi: <a href="https://doi.org/10.1101/2020.09.22.20199125" class="uri">https://doi.org/10.1101/2020.09.22.20199125</a></h4>
</div>
<div id="yuan-yuan-et.-al-cryo-em-structures-of-mers-cov-and-sars-cov-spike-glycoproteins-reveal-the-dynamic-receptor-binding-domains-nat-commun-8-15092-2017-httpsdoi.org10.1038ncomms15092" class="section level4">
<h4>Yuan Yuan, Et. al Cryo-EM structures of MERS-CoV and SARS-CoV spike glycoproteins reveal the dynamic receptor binding domains Nat Commun 8, 15092 (2017) <a href="https://doi.org/10.1038/ncomms15092" class="uri">https://doi.org/10.1038/ncomms15092</a></h4>
</div>
<div id="the-lanl-dataset-was-obtained-from-the-following-link-httpscov.lanl.govcomponentssequencecovanntannt.comp" class="section level4">
<h4>the lanl dataset was obtained from the following link: <a href="https://cov.lanl.gov/components/sequence/COV/annt/annt.comp" class="uri">https://cov.lanl.gov/components/sequence/COV/annt/annt.comp</a></h4>
</div>
</div>
</div>

         
      </div>
    </div>
  </div>
</div>

          </div>
      </div>
  </div>
  <script src="https://hzorkic.github.io/js/jquery.min.js"></script>
<script src="https://hzorkic.github.io/js/bootstrap.min.js"></script>
<script src="https://hzorkic.github.io/js/jquery.cookie.js"> </script>
<script src="https://hzorkic.github.io/js/ekko-lightbox.js"></script>
<script src="https://hzorkic.github.io/js/jquery.scrollTo.min.js"></script>
<script src="https://hzorkic.github.io/js/masonry.pkgd.min.js"></script>
<script src="https://hzorkic.github.io/js/imagesloaded.pkgd.min.js"></script>
<script src="https://hzorkic.github.io/js/owl.carousel.min.js"></script>
<script src="https://hzorkic.github.io/js/front.js"></script>



</body>
</html>
